POST {{authUrl}}/auth/login
Content-Type: application/json

{
  "username": "min",
  "password": "c663b11dff4be0badcf652212a2c1102"
}

> {% client.global.set("user_token",response.body.data.authority); %}

###
POST {{apiUrl}}/account/addAccount
Content-Type: application/json
Authorization: {{user_token}}

{
  "accountName": "现金",
  "currency": "CNY"
}

###
POST {{apiUrl}}/account/getAccountList
Content-Type: application/json
Authorization: {{user_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{apiUrl}}/tradeType/addExpendClassify
Content-Type: application/json
Authorization: {{user_token}}

{
  "seniorName": "交通",
  "secondName": "行车交通"
}

###
POST {{apiUrl}}/tradeType/addIncomeClassify
Content-Type: application/json
Authorization: {{user_token}}

{
  "seniorName": "交通",
  "secondName": "行车交通"
}

###
POST {{apiUrl}}/tradeType/getClassifyList
Content-Type: application/json
Authorization: {{user_token}}

{
  "direction": "INCOME"
}

###
POST {{apiUrl}}/tradeType/getClassifyBox
Content-Type: application/json
Authorization: {{user_token}}

{
  "direction": "EXPEND"
}

###
POST {{apiUrl}}/trade/addTradeRecord
Content-Type: application/json
Authorization: {{user_token}}

{
  "classifyId": 28,
  "amount": 1.5,
  "accountName": "支付宝",
  "accountId": 2,
  "remarks": "单车"
}

###
POST {{apiUrl}}/account/delAccount
Content-Type: application/json
Authorization: {{user_token}}

{
  "ids": [3]
}

###
POST {{apiUrl}}/account/getAccountDetail
Content-Type: application/json
Authorization: {{user_token}}

{
  "id": 1
}