spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/record_life_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: minnan.site
    port: 6379
    database: 2
    password: minnan

server:
  port: 8120

jwt:
  route:
    authentication:
      path: /recordApplets/auth/login,/recordApplets/auth/login/*
  header: Authorization
  expiration: 604800
  scret: czHao

logging:
  file:
    name: ./logs/recordlife.log

mybatis-plus:
  mapper-locations: /site/minnan/recordlife/domain/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  bucketName: link-server
  baseUrl: http://minnan.site:2000
  imageFolder: recordlife/image